name: Check for Vespa CLI version update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC daily
  push:
    branches:
      - "fix_ci_version"

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . requests # Assuming requests module is needed

      - name: Check latest version and set variables
        run: |
          set -x  # Print each command before executing it, for debugging
          python --version
          cat utils/check_latest_version.py
          version=$(python utils/check_latest_version.py)
          echo "::set-output version=$version"

      - name: Update the version
        if: env.version != 'NA'
        run: |
          python utils/update_version.py --version ${{ steps.check_latest_version.outputs.version }}

      - name: Commit the changes
        if: env.version != 'NA'
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            'pyproject.toml'
            'vespacli/_version_generated.py'
          default_author: github-actions[bot]
          message: "Update Vespa CLI version to ${{ steps.check_latest_version.outputs.version }}"
