name: Cross-Platform Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9] # Update or modify Python versions as needed
    env:
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Run installer
        run: python vespa_client/cli/installer.py

      - name: Verify installation
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            vespa version
          else
            source ~/.bash_profile || source ~/.bashrc || true
            vespa version
          fi
        shell: bash

      - name: Install test dependencies
        run: pip install -r requirements_dev.txt

      - name: Run tests with pytest
        run: pytest
